name: Detect fiducial

on:
  push:
    branches:
      - feat/fiducial-detect-run
    paths:
      - image/fiducial.tif
      - scripts/find_fiducial.py
      - .github/workflows/run-fiducial-detection.yml
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install opencv-python-headless numpy

      - name: Run detection
        run: |
          mkdir -p outputs
          python scripts/find_fiducial.py \
            --image image/fiducial.tif \
            --save outputs/fiducial_detection.png \
            --json-out outputs/fiducial_detection.json \
            --min-radius 10 \
            --param2 28

      - name: Add results to job summary
        run: |
          echo "Results JSON:" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo '```json' >> $GITHUB_STEP_SUMMARY
          cat outputs/fiducial_detection.json >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: fiducial-results
          path: outputs/

      - name: Commit outputs back to branch
        run: |
          if [ -n "$(git status --porcelain outputs)" ]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add outputs
            git commit -m "ci: add fiducial detection outputs"
            git push
          fi