name: Detect fiducial

on:
  push:
    branches:
      - '**'
    paths:
      - image/fiducial.tif
      - scripts/find_fiducial.py
      - .github/workflows/run-fiducial-detection.yml
  pull_request:
    paths:
      - image/fiducial.tif
      - scripts/find_fiducial.py
      - .github/workflows/run-fiducial-detection.yml
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref || github.ref }}
          fetch-depth: 0
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install opencv-python-headless numpy

      - name: Run detection
        run: |
          mkdir -p outputs
          python scripts/find_fiducial.py \
            --image image/fiducial.tif \
            --save outputs/fiducial_detection.png \
            --json-out outputs/fiducial_detection.json \
            --min-radius 10 \
            --param2 28

      - name: Add results to job summary
        run: |
          echo "Results JSON:" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo '```json' >> $GITHUB_STEP_SUMMARY
          cat outputs/fiducial_detection.json >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: fiducial-results
          path: outputs/

      - name: Commit outputs back to branch (best-effort)
        continue-on-error: true
        env:
          TARGET_BRANCH: ${{ github.head_ref || github.ref_name }}
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          if [ -n "$(git status --porcelain outputs)" ]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add outputs
            if git diff --cached --quiet; then
              echo "No changes to commit in outputs/"
            else
              git commit -m "ci: add fiducial detection outputs [skip ci]"
              echo "Attempting to push to ${TARGET_BRANCH}"
              git push origin HEAD:${TARGET_BRANCH} || echo "Push failed (likely PR from fork or no write permission)."
            fi
          else
            echo "No changes detected under outputs/."
          fi